services:
  - type: web
    name: alpha-quant
    env: python
    region: oregon  # Use Oregon for better performance
    plan: starter
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: "gunicorn --config gunicorn.conf.py main:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PIP_NO_CACHE_DIR
        value: "1"
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: "1"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: NUMEXPR_MAX_THREADS
        value: "1"
      - key: MALLOC_TRIM_THRESHOLD_
        value: "100000"
      - key: FLASK_ENV
        value: "production"